-- create table suspects (id int, name varchar(100), image varchar(200), profession varchar(200), handed varchar(10), spouse int, flavour varchar(300));
insert into suspects (id, name, handed) values (1, 'Suspect 01', 'left');
insert into suspects (id, name, handed) values (2, 'Suspect 02', 'left');
insert into suspects (id, name, handed) values (3, 'Suspect 03', 'left');
insert into suspects (id, name, handed) values (4, 'Suspect 04', 'left');
insert into suspects (id, name, handed) values (5, 'Suspect 05', 'left');
insert into suspects (id, name, handed) values (6, 'Suspect 06', 'right');
insert into suspects (id, name, handed) values (7, 'Suspect 07', 'right');
insert into suspects (id, name, handed) values (8, 'Suspect 08', 'right');
insert into suspects (id, name, handed) values (9, 'Suspect 09', 'right');
insert into suspects (id, name, handed) values (10,'Suspect 10', 'right');
insert into suspects (id, name, handed) values (11,'Suspect 11', 'left');
insert into suspects (id, name, handed) values (12,'Suspect 12', 'left');
insert into suspects (id, name, handed) values (13,'Suspect 13', 'left');
insert into suspects (id, name, handed) values (14,'Suspect 14', 'left');
insert into suspects (id, name, handed) values (15,'Suspect 15', 'left');
insert into suspects (id, name, handed) values (16,'Suspect 16', 'right');
insert into suspects (id, name, handed) values (17,'Suspect 17', 'right');
insert into suspects (id, name, handed) values (18,'Suspect 18', 'right');
insert into suspects (id, name, handed) values (19,'Suspect 19', 'right');
insert into suspects (id, name, handed) values (20,'Suspect 20', 'right');
